package com.virtualbeamer.constants;

public enum MessageType {
    DELETE_SESSION,
    HELLO,
    NEXT_SLIDE,
    PREVIOUS_SLIDE,
    SESSION_DETAILS,
    JOIN_SESSION,
    COLLECT_USERS_DATA,
    USER_DATA,
    LEAVE_SESSION,
    ELECT,
    COORD,
    STOP_ELECT,
    START_AGREEMENT_PROCESS,
    STOP_AGREEMENT_PROCESS,
    IM_ALIVE,
    CURRENT_SLIDE_NUMBER,
    NEW_PARTICIPANT,
    CHANGE_LEADER,
    MESSAGE_RESEND,
    SLIDE_RESEND,
    PASS_LEADERSHIP
}
